import type { GamePurchaseStatus, MediaType, PlexStatus, WatchStatus } from "@/lib/media";

export type MediaItemView = {
  id: string;
  mediaType: MediaType;
  title: string;
  originalTitle: string | null;
  coverLocalPath: string | null;
  sourceUrl: string | null;
  description: string | null;
  releaseYear: number | null;
  genres: string;
  status: WatchStatus;
  myRating: number | null;
  myReview: string | null;
  watchedAt: string | null;
  imdbId: string | null;
  tmdbId: string | null;
  bangumiId: string | null;
  igdbId: string | null;
  malId: string | null;
  isbn: string | null;
  plexRatingKey: string | null;
  plexStatus: PlexStatus | null;
  plexSyncedAt: string | null;
  gameProfile: GameProfileView | null;
  extraData: string | null;
  createdAt: string;
  updatedAt: string;
};

export type GameProfileView = {
  id: string;
  itemId: string;
  purchaseStatus: GamePurchaseStatus | null;
  primaryPlatform: string | null;
  ownedPlatforms: string;
  normalPriceCny: number | null;
  steamAppId: string | null;
  psnTitleId: string | null;
  psnConceptId: string | null;
  switchTitleId: string | null;
  playtimeForeverMinutes: number | null;
  playtime2WeeksMinutes: number | null;
  lastPlayedAt: string | null;
  externalIds: string | null;
  extraData: string | null;
  createdAt: string;
  updatedAt: string;
};
